config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#latest'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :movies, only: [:show] do
    collection do
      get :latest
      get :favourites
      get :search_movie
    end
    post :add_to_favourite_list
  end
  
  get :callback, to: 'tmdb_auth#callback'



  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
require_relative '.././services/tmdb_api_service.rb'
require 'json'

class MoviesController < ApplicationController
  include MovieHelper

  def latest
    movies = TmdbApiService.new.latest_movies
    @latest_movies = formatted_movies(movies)    
  end
  
  def search_movie
    movies = TmdbApiService.new.search_by_title(params[:title])
    @result = formatted_movies(movies)
  end

  def show
    movie = TmdbApiService.new.movie_details(params[:id])
    @formatted_movie = formatted_movie(movie) 
  end

  def add_to_favourite_list
    if params[:movie_id].present?
      @movie = TmdbApiService.new.add_to_favourite(params[:movie_id], session[:tmdb_session_id])
      set_session_id if @movie["success"].blank?
      @favourite_movies = TmdbApiService.new.favourites
      redirect_back(fallback_location: root_path, allow_other_host: false, notice: "Movie successfully added to the favourites.")
    else
      flash[:alert] = "Something went wrong !"
      redirect_back(fallback_location: root_path, allow_other_host: false)
    end    
  end
  
  def favourites
    movies = TmdbApiService.new.favourites()
    @favourites = formatted_movies(movies)
  end

  private
  def set_session_id
    request_token = TmdbApiService.new.request_token 
    callback_url = 'http://localhost:3000/callback'
    redirect_to "https://www.themoviedb.org/authenticate/#{request_token}?redirect_to=#{CGI.escape(callback_url)}", allow_other_host: true
  end
end

app/controllers/tmdb_auth_controller.rb
class TmdbAuthController < ApplicationController
  include HTTParty
  base_uri 'api.themoviedb.org/3/'
  format :json
  headers 'Accept' => 'application/json'
  headers 'Content-Type' => 'application/json'
  headers 'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1M2EwN2VmYWZiODFhN2FiMThhODY2N2QzOTBkNWJkMSIsInN1YiI6IjY0ZDUwNjNiZGI0ZWQ2MDBmZmI2ZjlkYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ._x7M1WYS8DE8ygy9hoPnbhMn_TW6lDzQ9a1KA0ZwXx8'
  @options = { query: { api_key: '53a07efafb81a7ab18a8667d390d5bd1' } }
  
  def callback
    request_token = params[:request_token]
    response = HTTParty.post("https://api.themoviedb.org/3/authentication/session/new?api_key=53a07efafb81a7ab18a8667d390d5bd1", body: { "request_token": request_token } )
    session[:tmdb_session_id] = JSON.parse(response.body)['session_id']
    redirect_to add_to_favourite_list_movies_path , notice: 'You are now authenticated with TMDb!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_helper.rb
module MovieHelper
  def formatted_movies(api_response)
    api_response["results"].map do |movie_data|
      {
        id: movie_data["id"],
        title: movie_data["title"],
        overview: movie_data["overview"],
        release_date: movie_data["release_date"],
        poster_path: movie_data["poster_path"]
      }
    end
  end
  
  def formatted_movie(movie_data)
    {
      title: movie_data["title"],
      release_date: movie_data["release_date"],
      overview: movie_data["overview"],
      poster_path: movie_data["poster_path"],
      genres: movie_data["genres"].map { |genre| genre["name"] }.join(", "),
      runtime: "#{movie_data["runtime"]} minutes",
      imdb_id: movie_data["imdb_id"],
      homepage: movie_data["homepage"],
      tagline: movie_data["tagline"],
      vote_average: "#{movie_data["vote_average"]} (#{movie_data["vote_count"]} votes)",
      revenue: "$#{movie_data["revenue"].to_s.reverse.scan(/\d{1,3}/).join(',').reverse}",
    }
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'movie' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_movies.html.erb
<%= render 'shared/navbar' %> 
<% if action == "latest" %> 
  <%= render 'shared/jmbotron' %>    
<% end %>

<div class="movies-container">
  <% movies.each do |movie| %>
    <% fav_movies = TmdbApiService.new.favourites %>
    <% @favourites = [] %>
    <% fav_movies["results"].each do |fav| %>
      <% @favourites.push(fav["id"]) %>
    <% end %>

    <div class="movie">
      <%= link_to movie_path(movie[:id]), target: "_blank" do %>
        <%= image_tag "https://image.tmdb.org/t/p/w500/#{movie[:poster_path]}", alt: movie['title'] %>
        <h3><%= movie[:title] %></h3>
      <% end %>
      <% if action == "latest" %>
        <% unless @favourites.include?(movie[:id]) %>     
          <%= button_to "Add to favourite", movie_add_to_favourite_list_path(movie[:id]), method: :post, class: "favourite" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
  
<% if action == "search_movie" && movies.blank? %>
  <div class="empty_movie">
    <h1>There is no such movie exist</h1>
  <div>
<% end %>

app/views/movies/favourites.html.erb
<%= render partial: "movies", locals: { movies: @favourites, action: "favourites" } %>

app/views/movies/latest.html.erb
<%= render partial: "movies", locals: { movies: @latest_movies, action: "latest" } %>

app/views/movies/search_movie.html.erb
<%= render partial: "movies", locals: { movies: @result, action: "search_movie" }%>

app/views/movies/show.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <%= image_tag "https://image.tmdb.org/t/p/w500/#{@formatted_movie[:poster_path]}", alt: @formatted_movie['title'], class: "movie-poster" %>
  <div class="formated-movie">
    <h1 class="movie-title"><%= @formatted_movie[:title] %></h1>
    <p class="release-date">Release Date: <%= @formatted_movie[:release_date] %></p>
    <div class="overview">
      <p><%= @formatted_movie[:overview] %></p>
    </div>
    <ul class="details-list">
      <li><strong>Genres:</strong> <%= @formatted_movie[:genres] %></li>
      <li><strong>Runtime:</strong> <%= @formatted_movie[:runtime] %></li>
      <li><strong>IMDB ID:</strong> <%= @formatted_movie[:imdb_id] %></li>
      <li><strong>Homepage:</strong> <%= link_to @formatted_movie[:homepage], target: "_blank" %></li>
      <li><strong>Tagline:</strong> <%= @formatted_movie[:tagline] %></li>
      <li><strong>Vote Average:</strong> <%= @formatted_movie[:vote_average] %></li>
      <li><strong>Revenue:</strong> <%= @formatted_movie[:revenue] %></li>
    </ul>
  </div>
</div>

app/views/shared/_jmbotron.html.erb
<div class="jumbotron">
<%# <%= render 'shared/navbar' %>
  <h1>Welcome to Movie List</h1>
  <p>Explore the latest movie releases</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top">
  <div class="nav-container">
    <ul class="navbar-nav nav-container-item">
      <li class="nav-item">
        <%= link_to latest_movies_path, class: "nav-link" do %>
          Home
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to favourites_movies_path, class: "nav-link" do %>
          Favourite Movies
        <% end %>
      </li>
    </ul>

    <%= form_tag(search_movie_movies_path, method: "get", class: "form-inline") do %>
      <%= text_field_tag(:title, params[:title], class: "form-control mr-sm-2", placeholder: "search by title", aria_label: "Search") %>
      <%= submit_tag("Search", class: "btn") %>
    <% end %>    
  </div>

  <div class="message-container">
    <% flash.each do |type, msg| %>
      <div class="message">
        <%= msg %>
      </div>
    <% end %>
  </div>
</nav>